version: "3"

includes:
  configs:
    taskfile: ./configs/taskfile.yml
    dir: ./configs
  nixos:
    taskfile: ./nixos/taskfile.yml
    dir: ./nixos

tasks:
  default:
    cmds:
      - chezmoi apply -v

  clean:
    cmds:
      - corepack cache clean

  init:
    prompt: This is a dangerous command... Do you want to continue?
    env:
      CHEZMOI_CONFIG_PATH: .config/chezmoi/chezmoi.toml
    cmds:
      - chezmoi init

      # TODO: For Windows
      - platform: [darwin, linux]
        cmd: nano $HOME/$CHEZMOI_CONFIG_PATH

      - task: configs:bbi
      - task: default
