version: '3'

tasks:
  default:
    platforms: [linux]
    cmds:
      - nh os switch . -- --impure

  gc:
    platforms: [linux]
    cmds:
      - nix-collect-garbage -d
      - nix-store --optimise -v

  update:
    platforms: [linux]
    cmds:
      - nix flake update
