version: "3"

tasks:
  default:
    platforms: [linux]
    cmds:
      - nixfmt .
      - nh os switch . -- --impure

  gc:
    platforms: [linux]
    cmds:
      - nh clean all -k 10 -K 14d
      - nix-store --optimise

  routine:
    platforms: [linux]
    deps: [update]
    cmds:
      - task: default

  update:
    platforms: [linux]
    cmds:
      - nix flake update
